# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-08 20:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(1, '待付款'), (2, '已付款'), (3, '已发货'), (4, '已收货'), (5, '待评价'), (6, '已评价')], default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(verbose_name='数量')),
                ('buy_money', models.DecimalField(decimal_places=2, max_digits=10)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='axf.Goods')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='axf.Order')),
            ],
        ),
    ]
